### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by cestep** [swimlane/swimlane-python#9]
There doesn't seem to be any documentation on the RTD link, and the readme is empty.  Is there any documentation available?

**Comment by nick-allen** [comment]
The update v2 isn't production yet, and the stable docs aren't yet available on the link in the repo. Check the latest docs (http://swimlane-python-driver.readthedocs.io/en/latest/) for the time being for v2, or the old doc pages on gitbook (https://swimlane.gitbooks.io/swimlane-python/content/) for earlier versions.
